[tool.isort]
profile = "black"

[tool.black]
line-length = 120
skip-string-normalization = true
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.env
  | \.venv
  | \.vscode
  | \.idea
)
'''

[tool.mypy]
ignore_missing_imports = true
no_implicit_optional = true
check_untyped_defs = false
strict_optional = false
warn_return_any = false
warn_unused_ignores = true
show_error_codes = true
exclude = [
    'env/',
    'env/',
    '.venv/',
    'venv/',
]
